# DO NOT DELETE
tokens = (
    'LOCATIONQUERY',
    'NAMESPACE',
    'VARIABLEASSIGNMENT',
    'UNKNOWNPOSITION',
    'EXPLICITPOSITION',
    'POSITIONCHANGE',
    'EXISTINGREFERENCE',
    'NEWREFERENCE',
    'INLINECOMMENT',
    'MULTILINECOMMENT'
)
