# DO NOT DELETE
tokens = (
    'LOCATIONQUERY',
    'NAMESPACE',
    'VARIABLEASSIGNMENT',
    'UNKNOWNLOCATION',
    'EXPLICITLOCATION',
    'LOCATIONTRANSITION',
    'EXISTINGREFERENCE',
    'NEWREFERENCE',
    'INLINECOMMENT',
    'MULTILINECOMMENT',
    'GETMOSTRECENTVARIABLE',
    'SETMOSTRECENTVARIABLE',
)
